const maps = [
  "2000AtmospheresAIE",
  "BerlingradAIE",
  "BlackburnAIE",
  "CuriousMindsAIE",
  "DeathAura506",
  "DeathAuraLE",
  "EternalEmpire506",
  "EternalEmpireLE",
  "EverDream506",
  "EverDreamLE",
  "GlitteringAshesAIE",
  "GoldenWall506",
  "GoldenWallLE",
  "HardwireAIE",
  "IceandChrome506",
  "IceandChromeLE",
  "InsideAndOutAIE",
  "JagannathaAIE",
  "JagannathaLE",
  "LightshadeAIE",
  "LightshadeLE",
  "MoondanceAIE",
  "OxideAIE",
  "OxideLE",
  "PillarsofGold506",
  "PillarsofGoldLE",
  "RomanticideAIE",
  "RomanticideLE",
  "StargazersAIE",
  "Submarine506",
  "SubmarineLE",
  "WaterfallAIE",
]

module.exports = maps;