//@ts-check
'use strict';

const { COMMANDCENTER, COMMANDCENTERFLYING, ORBITALCOMMAND, ORBITALCOMMANDFLYING, SUPPLYDEPOT, SUPPLYDEPOTLOWERED, BARRACKS, BARRACKSFLYING, FACTORY, FACTORYFLYING, STARPORT, STARPORTFLYING, GATEWAY, WARPGATE, HATCHERY, LAIR, BARRACKSREACTOR, FACTORYTECHLAB, STARPORTREACTOR } = require("@node-sc2/core/constants/unit-type");


const addOnTypes = {
  21: BARRACKSREACTOR,
  27: FACTORYTECHLAB,
  28: STARPORTREACTOR,
}

const countTypes = {
  18: [ COMMANDCENTER, COMMANDCENTERFLYING, ORBITALCOMMAND, ORBITALCOMMANDFLYING ],
  19: [ SUPPLYDEPOT, SUPPLYDEPOTLOWERED ],
  21: [ BARRACKS, BARRACKSFLYING ],
  27: [ FACTORY, FACTORYFLYING ],
  28: [ STARPORT, STARPORTFLYING ],
  38: [ BARRACKS, BARRACKSFLYING ],
  62: [ GATEWAY, WARPGATE ],
  86: [ HATCHERY, LAIR ],
  132: [ ORBITALCOMMAND, ORBITALCOMMANDFLYING ],
}  
module.exports = {
  addOnTypes,
  countTypes,
}