//@ts-check
'use strict';

const { COMMANDCENTER, COMMANDCENTERFLYING, ORBITALCOMMAND, ORBITALCOMMANDFLYING, SUPPLYDEPOT, SUPPLYDEPOTLOWERED, BARRACKS, BARRACKSFLYING, FACTORY, FACTORYFLYING, STARPORT, STARPORTFLYING, GATEWAY, WARPGATE, HATCHERY, LAIR, BARRACKSREACTOR, FACTORYTECHLAB, STARPORTREACTOR, EGG, LARVA, BANELINGCOCOON, RAVAGER, BANELING, LURKERMPBURROWED, SIEGETANK, SIEGETANKSIEGED, HELLION, HELLIONTANK, ROACH, HYDRALISK, ZERGLING, VIKINGFIGHTER, VIKINGASSAULT, WIDOWMINE, WIDOWMINEBURROWED } = require("@node-sc2/core/constants/unit-type");


const addOnTypes = {
  21: BARRACKSREACTOR,
  27: FACTORYTECHLAB,
  28: STARPORTREACTOR,
}

const flyingTypesMapping = new Map([
  [BARRACKSFLYING, BARRACKS],
  [FACTORYFLYING, FACTORY],
  [STARPORTFLYING, STARPORT],
]);

const countTypes = new Map([
  [BARRACKS, [ BARRACKS, BARRACKSFLYING ]],
  [COMMANDCENTER, [COMMANDCENTER, COMMANDCENTERFLYING, ORBITALCOMMAND, ORBITALCOMMANDFLYING] ],
  [FACTORY, [ FACTORY, FACTORYFLYING ]],
  [GATEWAY, [ GATEWAY, WARPGATE ]],
  [HATCHERY, [ HATCHERY, LAIR ]],
  [ORBITALCOMMAND, [ ORBITALCOMMAND, ORBITALCOMMANDFLYING ]],
  [STARPORT, [ STARPORT, STARPORTFLYING ]],
  [SUPPLYDEPOT, [ SUPPLYDEPOT, SUPPLYDEPOTLOWERED ]],
]);
const larvaOrEgg = [EGG, LARVA];

const morphMapping = {
  ROACH: [RAVAGER],
  HYDRALISK: [LURKERMPBURROWED],
  ZERGLING: [BANELING, BANELINGCOCOON],
}

module.exports = {
  addOnTypes,
  countTypes,
  flyingTypesMapping,
  larvaOrEgg,
  morphMapping,
}