const pvxStalkerColossiBuildOrder = {
  "name": "PvX - Easy Build - Stalker/Colossi v2",
  "race": "Protoss",
  "description": "A beginner-friendly build aiming for early pressure with a transition into Colossus/Stalker composition. Suitable against all races.",
  "steps": [
    { "supply": "14", "time": "0:20", "action": "Pylon" },
    { "supply": "15", "time": "0:40", "action": "Gateway" },
    { "supply": "16", "time": "0:48", "action": "Assimilator" },
    { "supply": "17", "time": "0:58", "action": "Assimilator" },
    { "supply": "19", "time": "1:13", "action": "Gateway" },
    { "supply": "20", "time": "1:28", "action": "Cybernetics Core" },
    { "supply": "20", "time": "1:37", "action": "Pylon" },
    { "supply": "23", "time": "2:02", "action": "Stalker x2 (Chrono Boost)" },
    { "supply": "27", "time": "2:08", "action": "Warp Gate" },
    { "supply": "27", "time": "2:24", "action": "Stalker x2" },
    { "supply": "31", "time": "2:36", "action": "Pylon" },
    { "supply": "31", "time": "2:56", "action": "Nexus" },
    { "supply": "32", "time": "3:10", "action": "Robotics Facility" },
    { "supply": "33", "time": "3:22", "action": "Pylon" },
    { "supply": "32", "time": "3:48", "action": "Gateway" },
    { "supply": "34", "time": "3:57", "action": "Observer (Chrono Boost)" },
    { "supply": "34", "time": "4:00", "action": "Robotics Bay" },
    { "supply": "35", "time": "4:06", "action": "Stalker x2" },
    { "supply": "43", "time": "4:27", "action": "Immortal (Chrono Boost)" },
    { "supply": "49", "time": "4:45", "action": "Assimilator x2" },
    { "supply": "51", "time": "4:55", "action": "Colossus (Chrono Boost)" },
    { "supply": "58", "time": "5:05", "action": "Extended Thermal Lance" },
    { "supply": "61", "time": "5:22", "action": "Pylon" },
    { "supply": "62", "time": "5:35", "action": "Nexus" },
    { "supply": "64", "time": "5:53", "action": "Colossus (Chrono Boost)" },
    { "supply": "72", "time": "6:02", "action": "Forge" },
    { "supply": "74", "time": "6:11", "action": "Stalker x2" },
    { "supply": "78", "time": "6:22", "action": "Gateway" },
    { "supply": "78", "time": "6:30", "action": "Protoss Ground Weapons Level 1 (Chrono Boost)" },
    { "supply": "78", "time": "6:36", "action": "Colossus (Chrono Boost)" },
    { "supply": "86", "time": "6:52", "action": "Twilight Council" },
    { "supply": "89", "time": "6:57", "action": "Stalker x2" },
    { "supply": "96", "time": "7:14", "action": "Photon Cannon x2" },
    { "supply": "99", "time": "7:24", "action": "Colossus (Chrono Boost)" },
    { "supply": "108", "time": "7:31", "action": "Charge" },
    { "supply": "109", "time": "7:48", "action": "Gateway x2" },
    { "supply": "109", "time": "7:58", "action": "Gateway" },
    { "supply": "117", "time": "8:08", "action": "Observer (Chrono Boost)" },
    { "supply": "124", "time": "8:20", "action": "Protoss Ground Weapons Level 2 (Chrono Boost)" },
    { "supply": "124", "time": "8:23", "action": "Colossus (Chrono Boost)" },
    { "supply": "133", "time": "8:38", "action": "Nexus" },
    { "supply": "144", "time": "9:07", "action": "Warp Prism (Chrono Boost)" },
    { "supply": "149", "time": "9:27", "action": "Gateway x3, Templar Archives" },
    { "supply": "149", "time": "9:36", "action": "Colossus (Chrono Boost)" }
  ]
};

module.exports = pvxStalkerColossiBuildOrder;
